version: '3'

services:
  python:
    build: .
    command: 'sleep 9999999'
    ports:
      - "8080:8080"
    volumes:
      - ./:/code
  clickhouse-server:
    container_name: aiochorm-server
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"

    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144